#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  DEFAULT_LOCALE,
  PUBLIC_LOCALES,
  SITE_URL,
  STATIC_I18N_ROUTES,
  buildHreflangLinks,
  getLocale,
  localizeHref,
  localizePath,
  localizeUrl,
} from "./i18n-locales.mjs";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT_DIR = path.join(ROOT_DIR, "content", "blog");
const BLOG_DIR = path.join(ROOT_DIR, "blog");
const MESSAGES_PATH = path.join(ROOT_DIR, "i18n", "messages.json");
const RSS_PATH = path.join(ROOT_DIR, "rss.xml");
const SITEMAP_PATH = path.join(ROOT_DIR, "sitemap.xml");
const POSTS_PER_PAGE = 5;
const DEFAULT_OG_IMAGE =
  "https://aroido.com/assets/aroido-brand/flame-raster/aroido-flame-social-og-dark-1200x630.png";
const GA_MEASUREMENT_ID = "G-WWH8VEQSRM";
const CHECK_ONLY = process.argv.includes("--check");
const GENERATED_NOTICE = "<!-- Generated by scripts/build-blog.mjs. Do not edit directly. -->";

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function readMessages() {
  return JSON.parse(fs.readFileSync(MESSAGES_PATH, "utf8"));
}

function getMessage(messages, localeCode, key) {
  const localeTable = messages[localeCode] || {};
  const defaultTable = messages[DEFAULT_LOCALE] || {};
  const value = Object.prototype.hasOwnProperty.call(localeTable, key)
    ? localeTable[key]
    : defaultTable[key];

  return typeof value === "string" ? value : "";
}

function formatMessage(messages, localeCode, key, replacements = {}) {
  let value = getMessage(messages, localeCode, key);
  for (const [replacementKey, replacementValue] of Object.entries(replacements)) {
    value = value.replaceAll(`{${replacementKey}}`, String(replacementValue));
  }
  return value;
}

function ensureDirectory(targetPath) {
  fs.mkdirSync(targetPath, { recursive: true });
}

function readMarkdownFiles(directoryPath) {
  if (!fs.existsSync(directoryPath)) {
    return [];
  }

  return fs
    .readdirSync(directoryPath)
    .filter((entry) => entry.endsWith(".md"))
    .sort()
    .map((entry) => path.join(directoryPath, entry));
}

function parseFrontmatter(source, filePath) {
  if (!source.startsWith("---\n")) {
    throw new Error(`Missing frontmatter block in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const endIndex = source.indexOf("\n---\n", 4);
  if (endIndex === -1) {
    throw new Error(`Unterminated frontmatter block in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const rawFrontmatter = source.slice(4, endIndex);
  const body = source.slice(endIndex + 5).trim();
  const metadata = {};
  let currentKey = null;

  for (const line of rawFrontmatter.split("\n")) {
    if (!line.trim()) {
      continue;
    }

    const listMatch = line.match(/^\s*-\s+(.+)\s*$/);
    if (listMatch && currentKey) {
      if (!Array.isArray(metadata[currentKey])) {
        metadata[currentKey] = [];
      }
      metadata[currentKey].push(parseFrontmatterValue(listMatch[1]));
      continue;
    }

    const fieldMatch = line.match(/^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/);
    if (!fieldMatch) {
      throw new Error(
        `Unsupported frontmatter line "${line}" in ${path.relative(ROOT_DIR, filePath)}`
      );
    }

    const [, key, rawValue] = fieldMatch;
    currentKey = key;
    metadata[key] = parseFrontmatterValue(rawValue);
  }

  return { metadata, body };
}

function parseFrontmatterValue(rawValue) {
  const value = String(rawValue || "").trim();

  if (!value) {
    return "";
  }

  if (value === "true") {
    return true;
  }

  if (value === "false") {
    return false;
  }

  if (value.startsWith("[") && value.endsWith("]")) {
    return value
      .slice(1, -1)
      .split(",")
      .map((entry) => entry.trim())
      .filter(Boolean)
      .map(stripWrappingQuotes);
  }

  return stripWrappingQuotes(value);
}

function stripWrappingQuotes(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }

  return value;
}

function slugifyTag(tag) {
  return String(tag || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function countWords(markdownBody) {
  return markdownBody
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]+`/g, " ")
    .replace(/!\[[^\]]*]\([^)]+\)/g, " ")
    .replace(/\[[^\]]+]\([^)]+\)/g, " ")
    .replace(/[#>*_~-]/g, " ")
    .split(/\s+/)
    .filter(Boolean).length;
}

function calculateReadingTime(markdownBody) {
  const words = countWords(markdownBody);
  const minutes = Math.max(1, Math.ceil(words / 220));
  return { words, minutes };
}

function getIntlLocale(localeCode) {
  return getLocale(localeCode).htmlLang;
}

function formatDisplayDate(date, localeCode = DEFAULT_LOCALE) {
  return new Intl.DateTimeFormat(getIntlLocale(localeCode), {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(date);
}

function formatRssDate(date) {
  return date.toUTCString();
}

function formatIsoDate(date) {
  return date.toISOString();
}

function formatSitemapDate(value) {
  return String(value).slice(0, 10);
}

function getSourceLastModifiedDate(relativePath) {
  try {
    const isoDate = execFileSync(
      "git",
      ["log", "-1", "--format=%cI", "--", relativePath],
      {
        cwd: ROOT_DIR,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }
    ).trim();

    if (isoDate) {
      return new Date(isoDate);
    }
  } catch (_error) {
    // Fall back to the filesystem timestamp outside of a git checkout.
  }

  return fs.statSync(path.join(ROOT_DIR, relativePath)).mtime;
}

function getGitLastModifiedIso(relativePath) {
  return formatSitemapDate(formatIsoDate(getSourceLastModifiedDate(relativePath)));
}

function validateAndNormalizePost(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const { metadata, body } = parseFrontmatter(source, filePath);
  const requiredFields = ["title", "date", "excerpt", "slug", "draft"];

  for (const field of requiredFields) {
    if (
      !Object.prototype.hasOwnProperty.call(metadata, field) ||
      metadata[field] === "" ||
      metadata[field] === undefined
    ) {
      throw new Error(`Missing "${field}" in ${path.relative(ROOT_DIR, filePath)}`);
    }
  }

  if (!/^[a-z0-9-]+$/.test(String(metadata.slug))) {
    throw new Error(`Invalid slug "${metadata.slug}" in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const parsedDate = new Date(String(metadata.date));
  if (Number.isNaN(parsedDate.getTime())) {
    throw new Error(`Invalid date "${metadata.date}" in ${path.relative(ROOT_DIR, filePath)}`);
  }

  if (!body) {
    throw new Error(`Empty markdown body in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const tags = Array.isArray(metadata.tags)
    ? metadata.tags.map((tag) => String(tag).trim()).filter(Boolean)
    : typeof metadata.tags === "string" && metadata.tags.trim()
      ? metadata.tags
          .split(",")
          .map((tag) => tag.trim())
          .filter(Boolean)
      : [];
  const readingTime = calculateReadingTime(body);
  const modifiedDate = getSourceLastModifiedDate(path.relative(ROOT_DIR, filePath));
  const coverImage = typeof metadata.coverImage === "string" ? metadata.coverImage.trim() : "";
  const socialImageUrl = coverImage.startsWith("/")
    ? `${SITE_URL}${coverImage}`
    : DEFAULT_OG_IMAGE;

  return {
    sourcePath: filePath,
    title: String(metadata.title),
    excerpt: String(metadata.excerpt),
    slug: String(metadata.slug),
    date: parsedDate,
    dateRaw: String(metadata.date),
    draft: Boolean(metadata.draft),
    tags,
    tagsWithSlugs: tags.map((tag) => ({ label: tag, slug: slugifyTag(tag) })),
    coverImage,
    body,
    html: renderMarkdown(body),
    displayDate: formatDisplayDate(parsedDate),
    isoDate: formatIsoDate(parsedDate),
    modifiedIsoDate: formatIsoDate(modifiedDate),
    rssDate: formatRssDate(parsedDate),
    readingMinutes: readingTime.minutes,
    wordCount: readingTime.words,
    path: `/blog/${metadata.slug}/`,
    canonicalUrl: `${SITE_URL}/blog/${metadata.slug}/`,
    socialImageUrl,
  };
}

function collectPublishedPosts() {
  const posts = readMarkdownFiles(CONTENT_DIR).map(validateAndNormalizePost);
  const slugSet = new Set();

  for (const post of posts) {
    if (slugSet.has(post.slug)) {
      throw new Error(`Duplicate slug "${post.slug}"`);
    }
    slugSet.add(post.slug);
  }

  return posts
    .filter((post) => !post.draft)
    .sort((left, right) => right.date.getTime() - left.date.getTime());
}

function renderInline(text) {
  const tokens = [];
  const stashToken = (html) => {
    const token = `%%INLINE_TOKEN_${tokens.length}%%`;
    tokens.push({ token, html });
    return token;
  };

  let html = text;

  html = html.replace(/!\[([^\]]*)\]\(([^)\s]+)(?:\s+"([^"]+)")?\)/g, (_match, alt, src, title) => {
    const titleAttribute = title ? ` title="${escapeHtml(title)}"` : "";
    return stashToken(
      `<img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}"${titleAttribute} loading="lazy" decoding="async" />`
    );
  });

  html = html.replace(/\[([^\]]+)\]\(([^)\s]+)(?:\s+"([^"]+)")?\)/g, (_match, label, href, title) => {
    const titleAttribute = title ? ` title="${escapeHtml(title)}"` : "";
    const isExternal = /^https?:\/\//i.test(href);
    const rel = isExternal ? ' rel="noreferrer"' : "";
    const target = isExternal ? ' target="_blank"' : "";
    return stashToken(
      `<a href="${escapeHtml(href)}"${titleAttribute}${rel}${target}>${escapeHtml(label)}</a>`
    );
  });

  html = html.replace(/`([^`]+)`/g, (_match, code) => stashToken(`<code>${escapeHtml(code)}</code>`));
  html = escapeHtml(html);
  html = html.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/(^|[\s(])\*([^*]+)\*(?=$|[\s).,!?])/g, "$1<em>$2</em>");
  tokens.forEach(({ token, html: tokenHtml }) => {
    html = html.replaceAll(token, tokenHtml);
  });
  return html;
}

function isHorizontalRule(line) {
  return /^(\*{3,}|-{3,}|_{3,})$/.test(line.trim());
}

function isOrderedListLine(line) {
  return /^\d+\.\s+/.test(line);
}

function isUnorderedListLine(line) {
  return /^[-*]\s+/.test(line);
}

function isHeadingLine(line) {
  return /^#{1,6}\s+/.test(line);
}

function isBlockQuoteLine(line) {
  return /^>\s?/.test(line);
}

function isFenceLine(line) {
  return /^```/.test(line.trim());
}

function isParagraphTerminator(line) {
  return (
    !line.trim() ||
    isHeadingLine(line) ||
    isFenceLine(line) ||
    isHorizontalRule(line) ||
    isOrderedListLine(line) ||
    isUnorderedListLine(line) ||
    isBlockQuoteLine(line)
  );
}

function renderMarkdown(markdown) {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const parts = [];

  for (let index = 0; index < lines.length; ) {
    const line = lines[index];

    if (!line.trim()) {
      index += 1;
      continue;
    }

    if (isFenceLine(line)) {
      const language = line.trim().slice(3).trim();
      const blockLines = [];
      index += 1;
      while (index < lines.length && !isFenceLine(lines[index])) {
        blockLines.push(lines[index]);
        index += 1;
      }
      if (index < lines.length) {
        index += 1;
      }
      const className = language ? ` class="language-${escapeHtml(language)}"` : "";
      parts.push(
        `<pre class="article-code"><code${className}>${escapeHtml(blockLines.join("\n"))}</code></pre>`
      );
      continue;
    }

    const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
    if (headingMatch) {
      const [, hashes, text] = headingMatch;
      const level = hashes.length;
      parts.push(`<h${level}>${renderInline(text.trim())}</h${level}>`);
      index += 1;
      continue;
    }

    if (isHorizontalRule(line)) {
      parts.push("<hr />");
      index += 1;
      continue;
    }

    if (isBlockQuoteLine(line)) {
      const quoteLines = [];
      while (index < lines.length && isBlockQuoteLine(lines[index])) {
        quoteLines.push(lines[index].replace(/^>\s?/, ""));
        index += 1;
      }
      const quoteHtml = quoteLines
        .join("\n")
        .split(/\n{2,}/)
        .map((paragraph) => `<p>${renderInline(paragraph.replace(/\n+/g, " ").trim())}</p>`)
        .join("");
      parts.push(`<blockquote>${quoteHtml}</blockquote>`);
      continue;
    }

    if (isUnorderedListLine(line) || isOrderedListLine(line)) {
      const ordered = isOrderedListLine(line);
      const tagName = ordered ? "ol" : "ul";
      const items = [];

      while (index < lines.length) {
        const current = lines[index];
        const matchesCurrent = ordered ? isOrderedListLine(current) : isUnorderedListLine(current);
        if (!matchesCurrent) {
          break;
        }

        const itemLines = [
          ordered
            ? current.replace(/^\d+\.\s+/, "")
            : current.replace(/^[-*]\s+/, ""),
        ];
        index += 1;

        while (index < lines.length) {
          const continuation = lines[index];
          if (!continuation.trim()) {
            index += 1;
            break;
          }
          if (
            isHeadingLine(continuation) ||
            isFenceLine(continuation) ||
            isHorizontalRule(continuation) ||
            isBlockQuoteLine(continuation) ||
            isOrderedListLine(continuation) ||
            isUnorderedListLine(continuation)
          ) {
            break;
          }
          itemLines.push(continuation.trim());
          index += 1;
        }

        items.push(`<li>${renderInline(itemLines.join(" "))}</li>`);
      }

      parts.push(`<${tagName}>${items.join("")}</${tagName}>`);
      continue;
    }

    const paragraphLines = [line.trim()];
    index += 1;
    while (index < lines.length && !isParagraphTerminator(lines[index])) {
      paragraphLines.push(lines[index].trim());
      index += 1;
    }
    parts.push(`<p>${renderInline(paragraphLines.join(" "))}</p>`);
  }

  return parts.join("\n");
}

function getAssetPrefix(routePath) {
  const segments = routePath
    .replace(/^\/+|\/+$/g, "")
    .split("/")
    .filter(Boolean);
  if (segments.length === 0) {
    return "./";
  }
  return "../".repeat(segments.length);
}

function renderLanguageSwitch(messages, localeCode, routePath) {
  const activeLocale = getLocale(localeCode);
  const ariaLabel = getMessage(messages, localeCode, "aria_language_switch") || "Language switch";
  const links = PUBLIC_LOCALES.map((locale) => {
    const activeAttributes =
      locale.code === activeLocale.code ? ' aria-current="true" aria-pressed="true"' : "";
    return `            <a class="lang-btn" href="${escapeHtml(
      localizePath(routePath, locale.code)
    )}" data-lang="${escapeHtml(locale.code)}" hreflang="${escapeHtml(
      locale.hreflang
    )}" lang="${escapeHtml(locale.htmlLang)}"${activeAttributes}>${escapeHtml(locale.label)}</a>`;
  }).join("\n");

  return `
          <nav class="lang-switch" aria-label="${escapeHtml(
            ariaLabel
          )}" data-i18n-aria-label="aria_language_switch">
${links}
          </nav>`;
}

function renderTopbar(currentSection, localeCode, routePath, messages) {
  const blogCurrent = currentSection === "blog" ? ' aria-current="page"' : "";
  const navHref = (pathValue) => localizePath(pathValue, localeCode);
  return `
      <header class="topbar reveal" data-reveal>
        <a class="brand brand-link brand-with-mark" href="${escapeHtml(navHref("/"))}">
          <img
            class="brand-mark"
            src="/assets/aroido-brand/flame-raster/aroido-flame-lockup-light-transparent-1600.png"
            data-mark-light="/assets/aroido-brand/flame-raster/aroido-flame-lockup-dark-transparent-1600.png"
            data-mark-dark="/assets/aroido-brand/flame-raster/aroido-flame-lockup-light-transparent-1600.png"
            alt="Aroido"
            width="140"
            height="56"
            decoding="async"
          />
        </a>
        <nav class="main-nav" aria-label="Main navigation" data-i18n-aria-label="aria_main_nav">
          <a href="${escapeHtml(navHref("/"))}" data-i18n="nav_home">${escapeHtml(getMessage(messages, localeCode, "nav_home"))}</a>
          <a href="${escapeHtml(navHref("/projects/"))}" data-i18n="nav_projects">${escapeHtml(getMessage(messages, localeCode, "nav_projects"))}</a>
          <a href="${escapeHtml(navHref("/blog/"))}" data-i18n="nav_blog"${blogCurrent}>${escapeHtml(getMessage(messages, localeCode, "nav_blog"))}</a>
          <a href="${escapeHtml(navHref("/team/"))}" data-i18n="nav_team">${escapeHtml(getMessage(messages, localeCode, "nav_team"))}</a>
          <a href="${escapeHtml(navHref("/contact/"))}" data-i18n="nav_contact">${escapeHtml(getMessage(messages, localeCode, "nav_contact"))}</a>
        </nav>
        <div class="header-controls">
${renderLanguageSwitch(messages, localeCode, routePath)}
          <div class="theme-switch" role="group" aria-label="Theme switch" data-i18n-aria-label="aria_theme_switch">
            <button class="theme-btn" data-theme-mode="auto" type="button" data-i18n="theme_auto">${escapeHtml(getMessage(messages, localeCode, "theme_auto"))}</button>
            <button class="theme-btn" data-theme-mode="light" type="button" data-i18n="theme_light">${escapeHtml(getMessage(messages, localeCode, "theme_light"))}</button>
            <button class="theme-btn" data-theme-mode="dark" type="button" data-i18n="theme_dark">${escapeHtml(getMessage(messages, localeCode, "theme_dark"))}</button>
          </div>
        </div>
      </header>`;
}

function renderDocument({
  routePath,
  localeCode = DEFAULT_LOCALE,
  title,
  description,
  canonicalPath = routePath,
  ogType = "website",
  ogImage = DEFAULT_OG_IMAGE,
  mainContent,
  structuredData,
  messages,
}) {
  const locale = getLocale(localeCode);
  const localizedPath = localizePath(canonicalPath, localeCode);
  const assetPrefix = getAssetPrefix(localizedPath);
  const cssHref = `${assetPrefix}styles.css`;
  const scriptSrc = `${assetPrefix}script.js`;
  const canonicalUrl = localizeUrl(canonicalPath, localeCode);
  const alternateLinks = buildHreflangLinks(canonicalPath)
    .map(
      (link) =>
        `    <link rel="alternate" hreflang="${escapeHtml(link.hreflang)}" href="${escapeHtml(
          link.href
        )}" />`
    )
    .join("\n");
  const jsonLd = JSON.stringify(structuredData, null, 2);
  const skipLabel = getMessage(messages || {}, localeCode, "skip_to_content") || "Skip to content";

  return `<!doctype html>
<html lang="${escapeHtml(locale.htmlLang)}" data-static-meta="true" data-locale="${escapeHtml(locale.code)}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(title)}</title>
    <meta id="metaDescription" name="description" content="${escapeHtml(description)}" />
    <link rel="canonical" href="${escapeHtml(canonicalUrl)}" />
${alternateLinks}
    <meta property="og:type" content="${escapeHtml(ogType)}" />
    <meta property="og:site_name" content="Aroido" />
    <meta property="og:locale" content="${escapeHtml(locale.ogLocale)}" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:url" content="${escapeHtml(canonicalUrl)}" />
    <meta property="og:image" content="${escapeHtml(ogImage)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${escapeHtml(ogImage)}" />
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/aroido-brand/flame-raster/aroido-flame-favicon-dark-32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/aroido-brand/flame-raster/aroido-flame-favicon-dark-16.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/aroido-brand/flame-raster/aroido-flame-apple-touch-icon-180.png" />
    <script type="application/ld+json">
${jsonLd}
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=IBM+Plex+Mono:wght@400;500&family=Space+Grotesk:wght@400;500;700&display=swap"
    />
    <script async src="https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      window.gtag = window.gtag || gtag;
      gtag("js", new Date());
      gtag("config", "${GA_MEASUREMENT_ID}");
    </script>
    <link rel="stylesheet" href="${escapeHtml(cssHref)}" />
  </head>
  <body>
    ${GENERATED_NOTICE}
    <a class="skip-link" href="#main-content" data-i18n="skip_to_content">${escapeHtml(skipLabel)}</a>
    <main id="main-content" class="site-shell">
${mainContent}
    </main>
    <script src="${escapeHtml(scriptSrc)}"></script>
  </body>
</html>
`;
}

function renderTagList(post) {
  if (!post.tagsWithSlugs.length) {
    return "";
  }

  return `<ul class="tag-list" aria-label="Post tags">${post.tagsWithSlugs
    .map((tag) => `<li>${escapeHtml(tag.label)}</li>`)
    .join("")}</ul>`;
}

function rewriteHtmlHrefs(html, localeCode) {
  return html.replace(/\shref="([^"]+)"/g, (match, href) => {
    const nextHref = localizeHref(href, localeCode);
    return ` href="${escapeHtml(nextHref)}"`;
  });
}

function formatPostCountLabel(messages, localeCode, count) {
  const key = count === 1 ? "blog_post_count_one" : "blog_post_count_other";
  return formatMessage(messages, localeCode, key, { count });
}

function formatReadingTime(messages, localeCode, minutes) {
  return formatMessage(messages, localeCode, "blog_reading_minutes", { count: minutes });
}

function formatWordCount(messages, localeCode, words) {
  return formatMessage(messages, localeCode, "blog_word_count", { count: words });
}

function renderPostCard(post, localeCode, messages) {
  const postPath = localizePath(post.path, localeCode);
  const coverMarkup = post.coverImage
    ? `
            <a class="blog-card-cover" href="${escapeHtml(postPath)}" aria-hidden="true" tabindex="-1">
              <img src="${escapeHtml(post.coverImage)}" alt="" loading="eager" decoding="async" />
            </a>`
    : "";

  return `
          <article class="blog-card">
            ${coverMarkup}
            <p class="mini-label">${escapeHtml(formatDisplayDate(post.date, localeCode))} · ${escapeHtml(formatReadingTime(messages, localeCode, post.readingMinutes))}</p>
            <h2><a href="${escapeHtml(postPath)}">${escapeHtml(post.title)}</a></h2>
            <p>${escapeHtml(post.excerpt)}</p>
            ${renderTagList(post)}
            <a class="inline-link" href="${escapeHtml(postPath)}" data-i18n="blog_read_more">${escapeHtml(getMessage(messages, localeCode, "blog_read_more"))}</a>
          </article>`;
}

function renderPagination(currentPage, totalPages, localeCode, messages) {
  if (totalPages <= 1) {
    return "";
  }

  const previousPath =
    currentPage > 1 ? (currentPage === 2 ? "/blog/" : `/blog/page/${currentPage - 1}/`) : null;
  const nextPath = currentPage < totalPages ? `/blog/page/${currentPage + 1}/` : null;
  const pageLinks = Array.from({ length: totalPages }, (_unused, offset) => {
    const pageNumber = offset + 1;
    const pagePath = pageNumber === 1 ? "/blog/" : `/blog/page/${pageNumber}/`;
    const current = pageNumber === currentPage ? ' aria-current="page"' : "";
    return `<a href="${escapeHtml(localizePath(pagePath, localeCode))}"${current}>${pageNumber}</a>`;
  }).join("");

  return `
      <nav class="pagination reveal" data-reveal aria-label="Blog pagination">
        <div class="pagination-edge">
          ${
            previousPath
              ? `<a class="pagination-link" href="${escapeHtml(localizePath(previousPath, localeCode))}" data-i18n="blog_pagination_prev">${escapeHtml(getMessage(messages, localeCode, "blog_pagination_prev"))}</a>`
              : `<span class="pagination-link is-disabled" data-i18n="blog_pagination_prev">${escapeHtml(getMessage(messages, localeCode, "blog_pagination_prev"))}</span>`
          }
        </div>
        <div class="pagination-pages">${pageLinks}</div>
        <div class="pagination-edge">
          ${
            nextPath
              ? `<a class="pagination-link" href="${escapeHtml(localizePath(nextPath, localeCode))}" data-i18n="blog_pagination_next">${escapeHtml(getMessage(messages, localeCode, "blog_pagination_next"))}</a>`
              : `<span class="pagination-link is-disabled" data-i18n="blog_pagination_next">${escapeHtml(getMessage(messages, localeCode, "blog_pagination_next"))}</span>`
          }
        </div>
      </nav>`;
}

function renderBlogIndexPage(posts, pageNumber, totalPages, localeCode, messages) {
  const archiveTitle =
    pageNumber === 1
      ? getMessage(messages, localeCode, "blog_archive_seo_title")
      : formatMessage(messages, localeCode, "blog_archive_seo_title_page", {
          page: pageNumber,
        });
  const archiveDescription =
    pageNumber === 1
      ? getMessage(messages, localeCode, "blog_archive_meta_description")
      : formatMessage(messages, localeCode, "blog_archive_meta_description_page", {
          page: pageNumber,
        });
  const routePath = pageNumber === 1 ? "/blog/" : `/blog/page/${pageNumber}/`;
  const canonicalPath = routePath;
  const listMarkup = posts.length
    ? posts.map((post) => renderPostCard(post, localeCode, messages)).join("\n")
    : `<p class="blog-empty" data-i18n="blog_posts_empty">${escapeHtml(
        getMessage(messages, localeCode, "blog_posts_empty")
      )}</p>`;
  const locale = getLocale(localeCode);
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name:
      pageNumber === 1
        ? getMessage(messages, localeCode, "blog_archive_structured_name")
        : formatMessage(messages, localeCode, "blog_archive_structured_name_page", {
            page: pageNumber,
          }),
    url: localizeUrl(canonicalPath, localeCode),
    inLanguage: locale.jsonLdLanguage,
    isPartOf: {
      "@type": "Blog",
      name: "Aroido Blog",
      url: localizeUrl("/blog/", localeCode),
    },
    mainEntity: {
      "@type": "ItemList",
      itemListElement: posts.map((post, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: localizeUrl(post.path, localeCode),
        name: post.title,
      })),
    },
  };

  const mainContent = `
${renderTopbar("blog", localeCode, routePath, messages)}
      <section class="page-hero blog-hero reveal" data-reveal>
        <p class="kicker" data-i18n="blog_eyebrow">${escapeHtml(getMessage(messages, localeCode, "blog_eyebrow"))}</p>
        <h1 data-i18n="blog_archive_h1">${escapeHtml(getMessage(messages, localeCode, "blog_archive_h1"))}</h1>
        <p class="blog-hero-copy">
          ${escapeHtml(getMessage(messages, localeCode, "blog_archive_copy"))}
        </p>
        <div class="blog-hero-meta">
          <span class="blog-pill">${escapeHtml(formatPostCountLabel(messages, localeCode, posts.length))}</span>
          <span class="blog-pill">${escapeHtml(
            formatMessage(messages, localeCode, "blog_page_count", {
              page: pageNumber,
              total: totalPages,
            })
          )}</span>
          <span class="blog-pill">${escapeHtml(getMessage(messages, localeCode, "blog_topic_pill"))}</span>
        </div>
      </section>

      <section class="section">
        <div class="section-head">
          <p class="section-eyebrow" data-i18n="blog_archive_label">${escapeHtml(getMessage(messages, localeCode, "blog_archive_label"))}</p>
          <h2>${escapeHtml(
            pageNumber === 1
              ? getMessage(messages, localeCode, "blog_archive_latest_entries")
              : formatMessage(messages, localeCode, "blog_archive_page_heading", {
                  page: pageNumber,
                })
          )}</h2>
          <p>${escapeHtml(getMessage(messages, localeCode, "blog_archive_intro"))}</p>
        </div>
        <div class="blog-grid">
${listMarkup}
        </div>
      </section>
${renderPagination(pageNumber, totalPages, localeCode, messages)}
      <section class="contact-panel">
        <h2 data-i18n="blog_footer_title">${escapeHtml(getMessage(messages, localeCode, "blog_footer_title"))}</h2>
        <p data-i18n="blog_footer_description">
          ${escapeHtml(getMessage(messages, localeCode, "blog_footer_description"))}
        </p>
        <div class="hero-actions">
          <a class="btn btn-primary" href="${escapeHtml(localizePath("/projects/", localeCode))}" data-i18n="blog_footer_primary">${escapeHtml(getMessage(messages, localeCode, "blog_footer_primary"))}</a>
          <a class="btn btn-ghost" href="${escapeHtml(localizePath("/contact/", localeCode))}" data-i18n="blog_footer_secondary">${escapeHtml(getMessage(messages, localeCode, "blog_footer_secondary"))}</a>
        </div>
      </section>`;

  return renderDocument({
    routePath,
    localeCode,
    title: archiveTitle,
    description: archiveDescription,
    canonicalPath,
    ogImage: DEFAULT_OG_IMAGE,
    mainContent,
    structuredData,
    messages,
  });
}

function getRelatedPosts(post, allPosts, limit = 3) {
  return allPosts
    .filter((candidate) => candidate.slug !== post.slug)
    .map((candidate) => {
      const sharedTagCount = candidate.tags.filter((tag) => post.tags.includes(tag)).length;
      return { candidate, sharedTagCount };
    })
    .sort((left, right) => {
      if (right.sharedTagCount !== left.sharedTagCount) {
        return right.sharedTagCount - left.sharedTagCount;
      }
      return right.candidate.date.getTime() - left.candidate.date.getTime();
    })
    .slice(0, limit)
    .map((entry) => entry.candidate);
}

function renderPostPage(post, index, allPosts, localeCode, messages) {
  const previousPost = allPosts[index - 1] || null;
  const nextPost = allPosts[index + 1] || null;
  const relatedPosts = getRelatedPosts(post, allPosts);
  const locale = getLocale(localeCode);
  const postUrl = localizeUrl(post.path, localeCode);
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.excerpt,
    datePublished: post.isoDate,
    dateModified: post.modifiedIsoDate,
    inLanguage: locale.jsonLdLanguage,
    mainEntityOfPage: postUrl,
    url: postUrl,
    keywords: post.tags,
    image: [post.socialImageUrl],
    author: {
      "@type": "Organization",
      name: "Aroido",
      url: SITE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: "Aroido",
      logo: {
        "@type": "ImageObject",
        url: "https://aroido.com/assets/aroido-brand/flame-raster/aroido-flame-app-icon-dark-512.png",
      },
    },
  };

  const articleNav = previousPost || nextPost
    ? `
          <nav class="article-nav" aria-label="Article navigation">
            ${
              previousPost
                ? `<a class="article-nav-card" href="${escapeHtml(localizePath(previousPost.path, localeCode))}">
                    <span class="mini-label" data-i18n="blog_article_nav_prev">${escapeHtml(getMessage(messages, localeCode, "blog_article_nav_prev"))}</span>
                    <strong>${escapeHtml(previousPost.title)}</strong>
                  </a>`
                : '<div class="article-nav-card is-empty" aria-hidden="true"></div>'
            }
            ${
              nextPost
                ? `<a class="article-nav-card" href="${escapeHtml(localizePath(nextPost.path, localeCode))}">
                    <span class="mini-label" data-i18n="blog_article_nav_next">${escapeHtml(getMessage(messages, localeCode, "blog_article_nav_next"))}</span>
                    <strong>${escapeHtml(nextPost.title)}</strong>
                  </a>`
                : '<div class="article-nav-card is-empty" aria-hidden="true"></div>'
            }
          </nav>`
    : "";

  const asideMarkup = relatedPosts.length
    ? `
          <aside class="article-aside">
            <div class="article-aside-card">
              <p class="section-eyebrow" data-i18n="blog_related_reads">${escapeHtml(getMessage(messages, localeCode, "blog_related_reads"))}</p>
              <ul class="article-recent-list">
                ${relatedPosts
                  .map(
                    (relatedPost) => `
                      <li>
                        <a href="${escapeHtml(localizePath(relatedPost.path, localeCode))}">${escapeHtml(relatedPost.title)}</a>
                        <span>${escapeHtml(relatedPost.excerpt)}</span>
                      </li>`
                  )
                  .join("")}
              </ul>
            </div>
          </aside>`
    : "";

  const mainContent = `
${renderTopbar("blog", localeCode, post.path, messages)}
      <article class="article-shell">
        <section class="article-hero reveal" data-reveal>
          <p class="kicker" data-i18n="blog_post_label">${escapeHtml(getMessage(messages, localeCode, "blog_post_label"))}</p>
          <a class="inline-link article-back-link" href="${escapeHtml(localizePath("/blog/", localeCode))}" data-i18n="blog_back_to_blog">${escapeHtml(getMessage(messages, localeCode, "blog_back_to_blog"))}</a>
          <h1>${escapeHtml(post.title)}</h1>
          <p class="article-excerpt">${escapeHtml(post.excerpt)}</p>
          <div class="article-meta">
            <span>${escapeHtml(formatDisplayDate(post.date, localeCode))}</span>
            <span>${escapeHtml(formatReadingTime(messages, localeCode, post.readingMinutes))}</span>
            <span>${escapeHtml(formatWordCount(messages, localeCode, post.wordCount))}</span>
          </div>
          ${renderTagList(post)}
        </section>

        <div class="article-layout">
          <section class="article-body">
            <div class="article-prose">
${rewriteHtmlHrefs(post.html, localeCode)}
            </div>
${articleNav}
          </section>
${asideMarkup}
        </div>
      </article>`;

  return renderDocument({
    routePath: post.path,
    localeCode,
    title: `${post.title} | Aroido Blog`,
    description: post.excerpt,
    canonicalPath: post.path,
    ogType: "article",
    ogImage: post.socialImageUrl,
    mainContent,
    structuredData,
    messages,
  });
}

function renderRss(posts) {
  const items = posts
    .map(
      (post) => `    <item>
      <title>${escapeHtml(post.title)}</title>
      <link>${escapeHtml(post.canonicalUrl)}</link>
      <guid>${escapeHtml(post.canonicalUrl)}</guid>
      <pubDate>${escapeHtml(post.rssDate)}</pubDate>
      <description>${escapeHtml(post.excerpt)}</description>
    </item>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Aroido Blog</title>
    <link>${SITE_URL}/blog/</link>
    <description>Product notes, release thinking, and operating decisions from Aroido.</description>
    <language>en-us</language>
${items}
  </channel>
</rss>
`;
}

function getFileLastModifiedIso(relativePath) {
  return getGitLastModifiedIso(relativePath);
}

function renderSitemap(posts, archivePages) {
  const latestPostIso = posts[0]?.isoDate || getFileLastModifiedIso("index.html");
  const canonicalEntries = [
    ...STATIC_I18N_ROUTES.map((route) => ({
      loc: route.routePath,
      lastmod: getFileLastModifiedIso(route.sourcePath),
    })),
    { loc: "/blog/", lastmod: archivePages[0]?.pagePosts[0]?.isoDate || latestPostIso },
    ...archivePages.slice(1).map((page) => ({
      loc: `/blog/page/${page.pageNumber}/`,
      lastmod: page.pagePosts[0]?.isoDate || latestPostIso,
    })),
    ...posts.map((post) => ({ loc: post.path, lastmod: post.isoDate })),
  ];
  const entries = PUBLIC_LOCALES.flatMap((locale) =>
    canonicalEntries.map((entry) => ({
      loc: localizePath(entry.loc, locale.code),
      lastmod: entry.lastmod,
    }))
  )
    .map(
      (entry) => `  <url>
    <loc>${escapeHtml(`${SITE_URL}${entry.loc}`)}</loc>
    <lastmod>${escapeHtml(entry.lastmod)}</lastmod>
  </url>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

function buildOutputMap(posts) {
  const messages = readMessages();
  const output = new Map();
  const totalPages = Math.max(1, Math.ceil(posts.length / POSTS_PER_PAGE));
  const archivePages = [];

  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    const startIndex = (pageNumber - 1) * POSTS_PER_PAGE;
    const pagePosts = posts.slice(startIndex, startIndex + POSTS_PER_PAGE);
    archivePages.push({ pageNumber, pagePosts });
    for (const locale of PUBLIC_LOCALES) {
      const localizedPath = localizePath(
        pageNumber === 1 ? "/blog/" : `/blog/page/${pageNumber}/`,
        locale.code
      );
      const relativeOutputPath = path.join(
        localizedPath.replace(/^\/|\/$/g, ""),
        "index.html"
      );
      output.set(
        relativeOutputPath,
        renderBlogIndexPage(pagePosts, pageNumber, totalPages, locale.code, messages)
      );
    }
  }

  posts.forEach((post, index) => {
    for (const locale of PUBLIC_LOCALES) {
      const localizedPath = localizePath(post.path, locale.code);
      const relativeOutputPath = path.join(
        localizedPath.replace(/^\/|\/$/g, ""),
        "index.html"
      );
      output.set(
        relativeOutputPath,
        renderPostPage(post, index, posts, locale.code, messages)
      );
    }
  });

  output.set("rss.xml", renderRss(posts));
  output.set("sitemap.xml", renderSitemap(posts, archivePages));
  return output;
}

function writeOutputs(outputMap) {
  fs.rmSync(BLOG_DIR, { recursive: true, force: true });
  for (const locale of PUBLIC_LOCALES.filter((entry) => entry.code !== DEFAULT_LOCALE)) {
    fs.rmSync(path.join(ROOT_DIR, locale.pathSegment, "blog"), { recursive: true, force: true });
  }

  for (const [relativePath, content] of outputMap.entries()) {
    const absolutePath = path.join(ROOT_DIR, relativePath);
    ensureDirectory(path.dirname(absolutePath));
    fs.writeFileSync(absolutePath, content, "utf8");
  }
}

function compareOutputs(outputMap) {
  const differences = [];

  for (const [relativePath, expected] of outputMap.entries()) {
    const absolutePath = path.join(ROOT_DIR, relativePath);
    if (!fs.existsSync(absolutePath)) {
      differences.push(`Missing generated file: ${relativePath}`);
      continue;
    }

    const current = fs.readFileSync(absolutePath, "utf8");
    if (current !== expected) {
      differences.push(`Outdated generated file: ${relativePath}`);
    }
  }

  if (fs.existsSync(BLOG_DIR)) {
    const actualBlogHtmlFiles = listFilesRecursively(BLOG_DIR)
      .filter((entry) => entry.endsWith(".html"))
      .map((entry) => path.relative(ROOT_DIR, entry));
    const expectedBlogHtmlFiles = Array.from(outputMap.keys()).filter((entry) =>
      entry.startsWith("blog/")
    );
    const expectedSet = new Set(expectedBlogHtmlFiles);

    for (const filePath of actualBlogHtmlFiles) {
      if (!expectedSet.has(filePath)) {
        differences.push(`Unexpected generated file: ${filePath}`);
      }
    }
  }

  for (const locale of PUBLIC_LOCALES.filter((entry) => entry.code !== DEFAULT_LOCALE)) {
    const localeBlogDir = path.join(ROOT_DIR, locale.pathSegment, "blog");
    if (!fs.existsSync(localeBlogDir)) {
      continue;
    }

    const actualLocalizedBlogHtmlFiles = listFilesRecursively(localeBlogDir)
      .filter((entry) => entry.endsWith(".html"))
      .map((entry) => path.relative(ROOT_DIR, entry));
    const expectedLocalizedSet = new Set(
      Array.from(outputMap.keys()).filter((entry) =>
        entry.startsWith(`${locale.pathSegment}/blog/`)
      )
    );

    for (const filePath of actualLocalizedBlogHtmlFiles) {
      if (!expectedLocalizedSet.has(filePath)) {
        differences.push(`Unexpected generated file: ${filePath}`);
      }
    }
  }

  return differences;
}

function listFilesRecursively(directoryPath) {
  const items = fs.readdirSync(directoryPath, { withFileTypes: true });
  const files = [];
  for (const item of items) {
    const fullPath = path.join(directoryPath, item.name);
    if (item.isDirectory()) {
      files.push(...listFilesRecursively(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

function main() {
  const posts = collectPublishedPosts();
  const outputMap = buildOutputMap(posts);

  if (CHECK_ONLY) {
    const differences = compareOutputs(outputMap);
    if (differences.length > 0) {
      console.error(differences.join("\n"));
      process.exit(1);
    }
    console.log("Blog output is up to date.");
    return;
  }

  writeOutputs(outputMap);
  console.log(`Generated ${posts.length} published posts into /blog with ${outputMap.size} artifacts.`);
}

main();
