#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT_DIR = path.join(ROOT_DIR, "content", "blog");
const BLOG_DIR = path.join(ROOT_DIR, "blog");
const RSS_PATH = path.join(ROOT_DIR, "rss.xml");
const SITEMAP_PATH = path.join(ROOT_DIR, "sitemap.xml");
const SITE_URL = "https://aroido.com";
const POSTS_PER_PAGE = 5;
const DEFAULT_OG_IMAGE =
  "https://aroido.com/assets/aroido-brand/flame-raster/aroido-flame-social-og-dark-1200x630.png";
const CHECK_ONLY = process.argv.includes("--check");
const GENERATED_NOTICE = "<!-- Generated by scripts/build-blog.mjs. Do not edit directly. -->";

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function ensureDirectory(targetPath) {
  fs.mkdirSync(targetPath, { recursive: true });
}

function readMarkdownFiles(directoryPath) {
  if (!fs.existsSync(directoryPath)) {
    return [];
  }

  return fs
    .readdirSync(directoryPath)
    .filter((entry) => entry.endsWith(".md"))
    .sort()
    .map((entry) => path.join(directoryPath, entry));
}

function parseFrontmatter(source, filePath) {
  if (!source.startsWith("---\n")) {
    throw new Error(`Missing frontmatter block in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const endIndex = source.indexOf("\n---\n", 4);
  if (endIndex === -1) {
    throw new Error(`Unterminated frontmatter block in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const rawFrontmatter = source.slice(4, endIndex);
  const body = source.slice(endIndex + 5).trim();
  const metadata = {};
  let currentKey = null;

  for (const line of rawFrontmatter.split("\n")) {
    if (!line.trim()) {
      continue;
    }

    const listMatch = line.match(/^\s*-\s+(.+)\s*$/);
    if (listMatch && currentKey) {
      if (!Array.isArray(metadata[currentKey])) {
        metadata[currentKey] = [];
      }
      metadata[currentKey].push(parseFrontmatterValue(listMatch[1]));
      continue;
    }

    const fieldMatch = line.match(/^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/);
    if (!fieldMatch) {
      throw new Error(
        `Unsupported frontmatter line "${line}" in ${path.relative(ROOT_DIR, filePath)}`
      );
    }

    const [, key, rawValue] = fieldMatch;
    currentKey = key;
    metadata[key] = parseFrontmatterValue(rawValue);
  }

  return { metadata, body };
}

function parseFrontmatterValue(rawValue) {
  const value = String(rawValue || "").trim();

  if (!value) {
    return "";
  }

  if (value === "true") {
    return true;
  }

  if (value === "false") {
    return false;
  }

  if (value.startsWith("[") && value.endsWith("]")) {
    return value
      .slice(1, -1)
      .split(",")
      .map((entry) => entry.trim())
      .filter(Boolean)
      .map(stripWrappingQuotes);
  }

  return stripWrappingQuotes(value);
}

function stripWrappingQuotes(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }

  return value;
}

function slugifyTag(tag) {
  return String(tag || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function countWords(markdownBody) {
  return markdownBody
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]+`/g, " ")
    .replace(/!\[[^\]]*]\([^)]+\)/g, " ")
    .replace(/\[[^\]]+]\([^)]+\)/g, " ")
    .replace(/[#>*_~-]/g, " ")
    .split(/\s+/)
    .filter(Boolean).length;
}

function calculateReadingTime(markdownBody) {
  const words = countWords(markdownBody);
  const minutes = Math.max(1, Math.ceil(words / 220));
  return { words, minutes };
}

function formatDisplayDate(date) {
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(date);
}

function formatRssDate(date) {
  return date.toUTCString();
}

function formatIsoDate(date) {
  return date.toISOString();
}

function validateAndNormalizePost(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const { metadata, body } = parseFrontmatter(source, filePath);
  const requiredFields = ["title", "date", "excerpt", "slug", "draft"];

  for (const field of requiredFields) {
    if (
      !Object.prototype.hasOwnProperty.call(metadata, field) ||
      metadata[field] === "" ||
      metadata[field] === undefined
    ) {
      throw new Error(`Missing "${field}" in ${path.relative(ROOT_DIR, filePath)}`);
    }
  }

  if (!/^[a-z0-9-]+$/.test(String(metadata.slug))) {
    throw new Error(`Invalid slug "${metadata.slug}" in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const parsedDate = new Date(String(metadata.date));
  if (Number.isNaN(parsedDate.getTime())) {
    throw new Error(`Invalid date "${metadata.date}" in ${path.relative(ROOT_DIR, filePath)}`);
  }

  if (!body) {
    throw new Error(`Empty markdown body in ${path.relative(ROOT_DIR, filePath)}`);
  }

  const tags = Array.isArray(metadata.tags)
    ? metadata.tags.map((tag) => String(tag).trim()).filter(Boolean)
    : typeof metadata.tags === "string" && metadata.tags.trim()
      ? metadata.tags
          .split(",")
          .map((tag) => tag.trim())
          .filter(Boolean)
      : [];
  const readingTime = calculateReadingTime(body);

  return {
    sourcePath: filePath,
    title: String(metadata.title),
    excerpt: String(metadata.excerpt),
    slug: String(metadata.slug),
    date: parsedDate,
    dateRaw: String(metadata.date),
    draft: Boolean(metadata.draft),
    tags,
    tagsWithSlugs: tags.map((tag) => ({ label: tag, slug: slugifyTag(tag) })),
    body,
    html: renderMarkdown(body),
    displayDate: formatDisplayDate(parsedDate),
    isoDate: formatIsoDate(parsedDate),
    rssDate: formatRssDate(parsedDate),
    readingMinutes: readingTime.minutes,
    wordCount: readingTime.words,
    path: `/blog/${metadata.slug}/`,
    canonicalUrl: `${SITE_URL}/blog/${metadata.slug}/`,
  };
}

function collectPublishedPosts() {
  const posts = readMarkdownFiles(CONTENT_DIR).map(validateAndNormalizePost);
  const slugSet = new Set();

  for (const post of posts) {
    if (slugSet.has(post.slug)) {
      throw new Error(`Duplicate slug "${post.slug}"`);
    }
    slugSet.add(post.slug);
  }

  return posts
    .filter((post) => !post.draft)
    .sort((left, right) => right.date.getTime() - left.date.getTime());
}

function renderInline(text) {
  const tokens = [];
  const stashToken = (html) => {
    const token = `%%INLINE_TOKEN_${tokens.length}%%`;
    tokens.push({ token, html });
    return token;
  };

  let html = text;

  html = html.replace(/!\[([^\]]*)\]\(([^)\s]+)(?:\s+"([^"]+)")?\)/g, (_match, alt, src, title) => {
    const titleAttribute = title ? ` title="${escapeHtml(title)}"` : "";
    return stashToken(
      `<img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}"${titleAttribute} loading="lazy" decoding="async" />`
    );
  });

  html = html.replace(/\[([^\]]+)\]\(([^)\s]+)(?:\s+"([^"]+)")?\)/g, (_match, label, href, title) => {
    const titleAttribute = title ? ` title="${escapeHtml(title)}"` : "";
    const isExternal = /^https?:\/\//i.test(href);
    const rel = isExternal ? ' rel="noreferrer"' : "";
    const target = isExternal ? ' target="_blank"' : "";
    return stashToken(
      `<a href="${escapeHtml(href)}"${titleAttribute}${rel}${target}>${escapeHtml(label)}</a>`
    );
  });

  html = html.replace(/`([^`]+)`/g, (_match, code) => stashToken(`<code>${escapeHtml(code)}</code>`));
  html = escapeHtml(html);
  html = html.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/(^|[\s(])\*([^*]+)\*(?=$|[\s).,!?])/g, "$1<em>$2</em>");
  tokens.forEach(({ token, html: tokenHtml }) => {
    html = html.replaceAll(token, tokenHtml);
  });
  return html;
}

function isHorizontalRule(line) {
  return /^(\*{3,}|-{3,}|_{3,})$/.test(line.trim());
}

function isOrderedListLine(line) {
  return /^\d+\.\s+/.test(line);
}

function isUnorderedListLine(line) {
  return /^[-*]\s+/.test(line);
}

function isHeadingLine(line) {
  return /^#{1,6}\s+/.test(line);
}

function isBlockQuoteLine(line) {
  return /^>\s?/.test(line);
}

function isFenceLine(line) {
  return /^```/.test(line.trim());
}

function isParagraphTerminator(line) {
  return (
    !line.trim() ||
    isHeadingLine(line) ||
    isFenceLine(line) ||
    isHorizontalRule(line) ||
    isOrderedListLine(line) ||
    isUnorderedListLine(line) ||
    isBlockQuoteLine(line)
  );
}

function renderMarkdown(markdown) {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const parts = [];

  for (let index = 0; index < lines.length; ) {
    const line = lines[index];

    if (!line.trim()) {
      index += 1;
      continue;
    }

    if (isFenceLine(line)) {
      const language = line.trim().slice(3).trim();
      const blockLines = [];
      index += 1;
      while (index < lines.length && !isFenceLine(lines[index])) {
        blockLines.push(lines[index]);
        index += 1;
      }
      if (index < lines.length) {
        index += 1;
      }
      const className = language ? ` class="language-${escapeHtml(language)}"` : "";
      parts.push(
        `<pre class="article-code"><code${className}>${escapeHtml(blockLines.join("\n"))}</code></pre>`
      );
      continue;
    }

    const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
    if (headingMatch) {
      const [, hashes, text] = headingMatch;
      const level = hashes.length;
      parts.push(`<h${level}>${renderInline(text.trim())}</h${level}>`);
      index += 1;
      continue;
    }

    if (isHorizontalRule(line)) {
      parts.push("<hr />");
      index += 1;
      continue;
    }

    if (isBlockQuoteLine(line)) {
      const quoteLines = [];
      while (index < lines.length && isBlockQuoteLine(lines[index])) {
        quoteLines.push(lines[index].replace(/^>\s?/, ""));
        index += 1;
      }
      const quoteHtml = quoteLines
        .join("\n")
        .split(/\n{2,}/)
        .map((paragraph) => `<p>${renderInline(paragraph.replace(/\n+/g, " ").trim())}</p>`)
        .join("");
      parts.push(`<blockquote>${quoteHtml}</blockquote>`);
      continue;
    }

    if (isUnorderedListLine(line) || isOrderedListLine(line)) {
      const ordered = isOrderedListLine(line);
      const tagName = ordered ? "ol" : "ul";
      const items = [];

      while (index < lines.length) {
        const current = lines[index];
        const matchesCurrent = ordered ? isOrderedListLine(current) : isUnorderedListLine(current);
        if (!matchesCurrent) {
          break;
        }

        const itemLines = [
          ordered
            ? current.replace(/^\d+\.\s+/, "")
            : current.replace(/^[-*]\s+/, ""),
        ];
        index += 1;

        while (index < lines.length) {
          const continuation = lines[index];
          if (!continuation.trim()) {
            index += 1;
            break;
          }
          if (
            isHeadingLine(continuation) ||
            isFenceLine(continuation) ||
            isHorizontalRule(continuation) ||
            isBlockQuoteLine(continuation) ||
            isOrderedListLine(continuation) ||
            isUnorderedListLine(continuation)
          ) {
            break;
          }
          itemLines.push(continuation.trim());
          index += 1;
        }

        items.push(`<li>${renderInline(itemLines.join(" "))}</li>`);
      }

      parts.push(`<${tagName}>${items.join("")}</${tagName}>`);
      continue;
    }

    const paragraphLines = [line.trim()];
    index += 1;
    while (index < lines.length && !isParagraphTerminator(lines[index])) {
      paragraphLines.push(lines[index].trim());
      index += 1;
    }
    parts.push(`<p>${renderInline(paragraphLines.join(" "))}</p>`);
  }

  return parts.join("\n");
}

function getAssetPrefix(routePath) {
  const segments = routePath
    .replace(/^\/+|\/+$/g, "")
    .split("/")
    .filter(Boolean);
  if (segments.length === 0) {
    return "./";
  }
  return "../".repeat(segments.length);
}

function renderTopbar(currentSection) {
  const blogCurrent = currentSection === "blog" ? ' aria-current="page"' : "";
  return `
      <header class="topbar reveal" data-reveal>
        <a class="brand brand-link brand-with-mark" href="/">
          <img
            class="brand-mark"
            src="/assets/aroido-brand/flame-raster/aroido-flame-lockup-light-transparent-1600.png"
            data-mark-light="/assets/aroido-brand/flame-raster/aroido-flame-lockup-dark-transparent-1600.png"
            data-mark-dark="/assets/aroido-brand/flame-raster/aroido-flame-lockup-light-transparent-1600.png"
            alt="Aroido"
            width="140"
            height="56"
            decoding="async"
          />
        </a>
        <nav class="main-nav" aria-label="Main navigation" data-i18n-aria-label="aria_main_nav">
          <a href="/" data-i18n="nav_home">Home</a>
          <a href="/projects/" data-i18n="nav_projects">Product</a>
          <a href="/blog/" data-i18n="nav_blog"${blogCurrent}>Blog</a>
          <a href="/team/" data-i18n="nav_team">Team</a>
          <a href="/contact/" data-i18n="nav_contact">Contact</a>
        </nav>
        <div class="header-controls">
          <div class="theme-switch" role="group" aria-label="Theme switch" data-i18n-aria-label="aria_theme_switch">
            <button class="theme-btn" data-theme-mode="auto" type="button" data-i18n="theme_auto">Auto</button>
            <button class="theme-btn" data-theme-mode="light" type="button" data-i18n="theme_light">Light</button>
            <button class="theme-btn" data-theme-mode="dark" type="button" data-i18n="theme_dark">Dark</button>
          </div>
        </div>
      </header>`;
}

function renderDocument({
  routePath,
  title,
  description,
  canonicalPath,
  ogType = "website",
  mainContent,
  structuredData,
}) {
  const assetPrefix = getAssetPrefix(routePath);
  const cssHref = `${assetPrefix}styles.css`;
  const scriptSrc = `${assetPrefix}script.js`;
  const canonicalUrl = `${SITE_URL}${canonicalPath}`;
  const jsonLd = JSON.stringify(structuredData, null, 2);

  return `<!doctype html>
<html lang="en" data-static-meta="true">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(title)}</title>
    <meta id="metaDescription" name="description" content="${escapeHtml(description)}" />
    <link rel="canonical" href="${escapeHtml(canonicalUrl)}" />
    <link rel="alternate" hreflang="en" href="${escapeHtml(`${canonicalUrl}?lang=en`)}" />
    <link rel="alternate" hreflang="x-default" href="${escapeHtml(canonicalUrl)}" />
    <meta property="og:type" content="${escapeHtml(ogType)}" />
    <meta property="og:site_name" content="Aroido" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:url" content="${escapeHtml(canonicalUrl)}" />
    <meta property="og:image" content="${escapeHtml(DEFAULT_OG_IMAGE)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${escapeHtml(DEFAULT_OG_IMAGE)}" />
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/aroido-brand/flame-raster/aroido-flame-favicon-dark-32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/aroido-brand/flame-raster/aroido-flame-favicon-dark-16.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/aroido-brand/flame-raster/aroido-flame-apple-touch-icon-180.png" />
    <script type="application/ld+json">
${jsonLd}
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=IBM+Plex+Mono:wght@400;500&family=Space+Grotesk:wght@400;500;700&display=swap"
    />
    <link rel="stylesheet" href="${escapeHtml(cssHref)}" />
  </head>
  <body>
    ${GENERATED_NOTICE}
    <a class="skip-link" href="#main-content" data-i18n="skip_to_content">Skip to content</a>
    <main id="main-content" class="site-shell">
${mainContent}
    </main>
    <script src="${escapeHtml(scriptSrc)}"></script>
  </body>
</html>
`;
}

function renderTagList(post) {
  if (!post.tagsWithSlugs.length) {
    return "";
  }

  return `<ul class="tag-list" aria-label="Post tags">${post.tagsWithSlugs
    .map((tag) => `<li>${escapeHtml(tag.label)}</li>`)
    .join("")}</ul>`;
}

function formatPostCountLabel(count) {
  return `${count} ${count === 1 ? "post" : "posts"} on this page`;
}

function renderPostCard(post) {
  return `
          <article class="blog-card">
            <p class="mini-label">${escapeHtml(post.displayDate)} · ${post.readingMinutes} min read</p>
            <h2><a href="${escapeHtml(post.path)}">${escapeHtml(post.title)}</a></h2>
            <p>${escapeHtml(post.excerpt)}</p>
            ${renderTagList(post)}
            <a class="inline-link" href="${escapeHtml(post.path)}" data-i18n="blog_read_more">Read article</a>
          </article>`;
}

function renderPagination(currentPage, totalPages) {
  if (totalPages <= 1) {
    return "";
  }

  const previousPath =
    currentPage > 1 ? (currentPage === 2 ? "/blog/" : `/blog/page/${currentPage - 1}/`) : null;
  const nextPath = currentPage < totalPages ? `/blog/page/${currentPage + 1}/` : null;
  const pageLinks = Array.from({ length: totalPages }, (_unused, offset) => {
    const pageNumber = offset + 1;
    const pagePath = pageNumber === 1 ? "/blog/" : `/blog/page/${pageNumber}/`;
    const current = pageNumber === currentPage ? ' aria-current="page"' : "";
    return `<a href="${pagePath}"${current}>${pageNumber}</a>`;
  }).join("");

  return `
      <nav class="pagination reveal" data-reveal aria-label="Blog pagination">
        <div class="pagination-edge">
          ${
            previousPath
              ? `<a class="pagination-link" href="${previousPath}" data-i18n="blog_pagination_prev">Previous</a>`
              : `<span class="pagination-link is-disabled" data-i18n="blog_pagination_prev">Previous</span>`
          }
        </div>
        <div class="pagination-pages">${pageLinks}</div>
        <div class="pagination-edge">
          ${
            nextPath
              ? `<a class="pagination-link" href="${nextPath}" data-i18n="blog_pagination_next">Next</a>`
              : `<span class="pagination-link is-disabled" data-i18n="blog_pagination_next">Next</span>`
          }
        </div>
      </nav>`;
}

function renderBlogIndexPage(posts, pageNumber, totalPages) {
  const archiveTitle =
    pageNumber === 1 ? "Aroido Blog | Notes From the Build Loop" : `Aroido Blog | Archive Page ${pageNumber}`;
  const archiveDescription =
    pageNumber === 1
      ? "Product notes, release thinking, and operating decisions from Aroido."
      : `Archive page ${pageNumber} for Aroido blog posts on product, delivery, and AI repo operations.`;
  const routePath = pageNumber === 1 ? "/blog/" : `/blog/page/${pageNumber}/`;
  const canonicalPath = routePath;
  const listMarkup = posts.length
    ? posts.map(renderPostCard).join("\n")
    : '<p class="blog-empty" data-i18n="blog_posts_empty">No posts published yet.</p>';
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: pageNumber === 1 ? "Aroido Blog" : `Aroido Blog Archive Page ${pageNumber}`,
    url: `${SITE_URL}${canonicalPath}`,
    inLanguage: "en-US",
    isPartOf: {
      "@type": "Blog",
      name: "Aroido Blog",
      url: `${SITE_URL}/blog/`,
    },
    mainEntity: {
      "@type": "ItemList",
      itemListElement: posts.map((post, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: post.canonicalUrl,
        name: post.title,
      })),
    },
  };

  const mainContent = `
${renderTopbar("blog")}
      <section class="page-hero blog-hero reveal" data-reveal>
        <p class="kicker" data-i18n="blog_eyebrow">Journal</p>
        <h1 data-i18n="blog_listing_title">Writing from the build loop.</h1>
        <p class="blog-hero-copy" data-i18n="blog_listing_description">
          Product notes, release thinking, and operating decisions from Aroido.
        </p>
        <div class="blog-hero-meta">
          <span class="blog-pill">${formatPostCountLabel(posts.length)}</span>
          <span class="blog-pill">Page ${pageNumber} of ${totalPages}</span>
          <span class="blog-pill">English posts for now</span>
        </div>
      </section>

      <section class="section reveal" data-reveal>
        <div class="section-head">
          <p class="section-eyebrow" data-i18n="blog_archive_label">Archive</p>
          <h2>${pageNumber === 1 ? "Latest entries" : `Archive page ${pageNumber}`}</h2>
        </div>
        <div class="blog-grid">
${listMarkup}
        </div>
      </section>
${renderPagination(pageNumber, totalPages)}
      <section class="contact-panel reveal" data-reveal>
        <h2 data-i18n="blog_footer_title">Need product context before you read deeper?</h2>
        <p data-i18n="blog_footer_description">
          Start with the current public product page, then come back here for the reasoning and release notes behind the work.
        </p>
        <div class="hero-actions">
          <a class="btn btn-primary" href="/projects/vibesmith/" data-i18n="blog_footer_primary">See VibeSmith</a>
          <a class="btn btn-ghost" href="/contact/" data-i18n="blog_footer_secondary">Contact Aroido</a>
        </div>
      </section>`;

  return renderDocument({
    routePath,
    title: archiveTitle,
    description: archiveDescription,
    canonicalPath,
    mainContent,
    structuredData,
  });
}

function renderPostPage(post, index, allPosts) {
  const previousPost = allPosts[index - 1] || null;
  const nextPost = allPosts[index + 1] || null;
  const recentPosts = allPosts.filter((candidate) => candidate.slug !== post.slug).slice(0, 3);
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.excerpt,
    datePublished: post.isoDate,
    dateModified: post.isoDate,
    inLanguage: "en-US",
    mainEntityOfPage: post.canonicalUrl,
    url: post.canonicalUrl,
    keywords: post.tags,
    author: {
      "@type": "Organization",
      name: "Aroido",
      url: SITE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: "Aroido",
      logo: {
        "@type": "ImageObject",
        url: "https://aroido.com/assets/aroido-brand/flame-raster/aroido-flame-app-icon-dark-512.png",
      },
    },
  };

  const articleNav = previousPost || nextPost
    ? `
          <nav class="article-nav" aria-label="Article navigation">
            ${
              previousPost
                ? `<a class="article-nav-card" href="${previousPost.path}">
                    <span class="mini-label" data-i18n="blog_article_nav_prev">Previous article</span>
                    <strong>${escapeHtml(previousPost.title)}</strong>
                  </a>`
                : '<div class="article-nav-card is-empty" aria-hidden="true"></div>'
            }
            ${
              nextPost
                ? `<a class="article-nav-card" href="${nextPost.path}">
                    <span class="mini-label" data-i18n="blog_article_nav_next">Next article</span>
                    <strong>${escapeHtml(nextPost.title)}</strong>
                  </a>`
                : '<div class="article-nav-card is-empty" aria-hidden="true"></div>'
            }
          </nav>`
    : "";

  const asideMarkup = recentPosts.length
    ? `
          <aside class="article-aside">
            <div class="article-aside-card">
              <p class="section-eyebrow" data-i18n="blog_recent_label">Recent posts</p>
              <ul class="article-recent-list">
                ${recentPosts
                  .map(
                    (recentPost) => `
                      <li>
                        <a href="${recentPost.path}">${escapeHtml(recentPost.title)}</a>
                        <span>${escapeHtml(recentPost.displayDate)}</span>
                      </li>`
                  )
                  .join("")}
              </ul>
            </div>
          </aside>`
    : "";

  const mainContent = `
${renderTopbar("blog")}
      <article class="article-shell">
        <section class="article-hero reveal" data-reveal>
          <p class="kicker" data-i18n="blog_post_label">Blog post</p>
          <a class="inline-link article-back-link" href="/blog/" data-i18n="blog_back_to_blog">Back to blog</a>
          <h1>${escapeHtml(post.title)}</h1>
          <p class="article-excerpt">${escapeHtml(post.excerpt)}</p>
          <div class="article-meta">
            <span>${escapeHtml(post.displayDate)}</span>
            <span>${post.readingMinutes} min read</span>
            <span>${post.wordCount} words</span>
          </div>
          ${renderTagList(post)}
        </section>

        <div class="article-layout">
          <section class="article-body reveal" data-reveal>
            <div class="article-prose">
${post.html}
            </div>
${articleNav}
          </section>
${asideMarkup}
        </div>
      </article>`;

  return renderDocument({
    routePath: post.path,
    title: `${post.title} | Aroido Blog`,
    description: post.excerpt,
    canonicalPath: post.path,
    ogType: "article",
    mainContent,
    structuredData,
  });
}

function renderRss(posts) {
  const items = posts
    .map(
      (post) => `    <item>
      <title>${escapeHtml(post.title)}</title>
      <link>${escapeHtml(post.canonicalUrl)}</link>
      <guid>${escapeHtml(post.canonicalUrl)}</guid>
      <pubDate>${escapeHtml(post.rssDate)}</pubDate>
      <description>${escapeHtml(post.excerpt)}</description>
    </item>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Aroido Blog</title>
    <link>${SITE_URL}/blog/</link>
    <description>Product notes, release thinking, and operating decisions from Aroido.</description>
    <language>en-us</language>
${items}
  </channel>
</rss>
`;
}

function getFileLastModifiedIso(relativePath) {
  return formatIsoDate(fs.statSync(path.join(ROOT_DIR, relativePath)).mtime);
}

function renderSitemap(posts, archivePages) {
  const latestPostIso = posts[0]?.isoDate || getFileLastModifiedIso("index.html");
  const entries = [
    { loc: "/", lastmod: getFileLastModifiedIso("index.html") },
    { loc: "/projects/", lastmod: getFileLastModifiedIso(path.join("projects", "index.html")) },
    {
      loc: "/projects/vibesmith/",
      lastmod: getFileLastModifiedIso(path.join("projects", "vibesmith", "index.html")),
    },
    { loc: "/team/", lastmod: getFileLastModifiedIso(path.join("team", "index.html")) },
    { loc: "/contact/", lastmod: getFileLastModifiedIso(path.join("contact", "index.html")) },
    { loc: "/blog/", lastmod: archivePages[0]?.pagePosts[0]?.isoDate || latestPostIso },
    ...archivePages.slice(1).map((page) => ({
      loc: `/blog/page/${page.pageNumber}/`,
      lastmod: page.pagePosts[0]?.isoDate || latestPostIso,
    })),
    ...posts.map((post) => ({ loc: post.path, lastmod: post.isoDate })),
  ]
    .map(
      (entry) => `  <url>
    <loc>${escapeHtml(`${SITE_URL}${entry.loc}`)}</loc>
    <lastmod>${escapeHtml(entry.lastmod)}</lastmod>
  </url>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries}
</urlset>
`;
}

function buildOutputMap(posts) {
  const output = new Map();
  const totalPages = Math.max(1, Math.ceil(posts.length / POSTS_PER_PAGE));
  const archivePages = [];

  for (let pageNumber = 1; pageNumber <= totalPages; pageNumber += 1) {
    const startIndex = (pageNumber - 1) * POSTS_PER_PAGE;
    const pagePosts = posts.slice(startIndex, startIndex + POSTS_PER_PAGE);
    archivePages.push({ pageNumber, pagePosts });
    const relativeOutputPath =
      pageNumber === 1
        ? path.join("blog", "index.html")
        : path.join("blog", "page", String(pageNumber), "index.html");
    output.set(relativeOutputPath, renderBlogIndexPage(pagePosts, pageNumber, totalPages));
  }

  posts.forEach((post, index) => {
    output.set(path.join("blog", post.slug, "index.html"), renderPostPage(post, index, posts));
  });

  output.set("rss.xml", renderRss(posts));
  output.set("sitemap.xml", renderSitemap(posts, archivePages));
  return output;
}

function writeOutputs(outputMap) {
  fs.rmSync(BLOG_DIR, { recursive: true, force: true });

  for (const [relativePath, content] of outputMap.entries()) {
    const absolutePath = path.join(ROOT_DIR, relativePath);
    ensureDirectory(path.dirname(absolutePath));
    fs.writeFileSync(absolutePath, content, "utf8");
  }
}

function compareOutputs(outputMap) {
  const differences = [];

  for (const [relativePath, expected] of outputMap.entries()) {
    const absolutePath = path.join(ROOT_DIR, relativePath);
    if (!fs.existsSync(absolutePath)) {
      differences.push(`Missing generated file: ${relativePath}`);
      continue;
    }

    const current = fs.readFileSync(absolutePath, "utf8");
    if (current !== expected) {
      differences.push(`Outdated generated file: ${relativePath}`);
    }
  }

  if (fs.existsSync(BLOG_DIR)) {
    const actualBlogHtmlFiles = listFilesRecursively(BLOG_DIR)
      .filter((entry) => entry.endsWith(".html"))
      .map((entry) => path.relative(ROOT_DIR, entry));
    const expectedBlogHtmlFiles = Array.from(outputMap.keys()).filter((entry) => entry.startsWith("blog/"));
    const expectedSet = new Set(expectedBlogHtmlFiles);

    for (const filePath of actualBlogHtmlFiles) {
      if (!expectedSet.has(filePath)) {
        differences.push(`Unexpected generated file: ${filePath}`);
      }
    }
  }

  return differences;
}

function listFilesRecursively(directoryPath) {
  const items = fs.readdirSync(directoryPath, { withFileTypes: true });
  const files = [];
  for (const item of items) {
    const fullPath = path.join(directoryPath, item.name);
    if (item.isDirectory()) {
      files.push(...listFilesRecursively(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

function main() {
  const posts = collectPublishedPosts();
  const outputMap = buildOutputMap(posts);

  if (CHECK_ONLY) {
    const differences = compareOutputs(outputMap);
    if (differences.length > 0) {
      console.error(differences.join("\n"));
      process.exit(1);
    }
    console.log("Blog output is up to date.");
    return;
  }

  writeOutputs(outputMap);
  console.log(`Generated ${posts.length} published posts into /blog with ${outputMap.size} artifacts.`);
}

main();
